# Generated by Django 5.0.1 on 2024-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_age_remove_user_playerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='playerID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
