# Generated by Django 4.2.8 on 2024-03-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "courtID",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("availability", models.CharField(default="Available", max_length=50)),
                ("num_availability", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=255)),
                (
                    "court_image",
                    models.ImageField(blank=True, null=True, upload_to="court_images/"),
                ),
            ],
        ),
    ]
