# Generated by Django 5.0.1 on 2024-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('courtID', models.AutoField(primary_key=True, serialize=False)),
                ('num_availability', models.PositiveIntegerField()),
                ('availabilityTag', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('court_image', models.ImageField(blank=True, null=True, upload_to='court_images/')),
            ],
        ),
    ]
