# Generated by Django 5.0.1 on 2024-02-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='availabilityTag',
        ),
        migrations.AddField(
            model_name='court',
            name='availability',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='court',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='courtID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
