# Generated by Django 4.2.8 on 2024-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="court",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
