# Generated by Django 4.2.8 on 2024-03-05 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("gameID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="courts.court",
                    ),
                ),
            ],
        ),
    ]
