# Generated by Django 5.0.1 on 2024-02-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='courts.court')),
            ],
        ),
    ]
