# Generated by Django 4.2.8 on 2024-03-05 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="players_associated",
            field=models.ManyToManyField(
                related_name="games", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
